#define UNLOCK_OPCODE         'A'
#define LOCK_OPCODE           'B'
#define BIOAUTH_OPCODE        'C'
#define OTPAUTH_OPCODE        'D'
#define RESET_OPCODE          'E'
#define ENROLL_BIO_OPCODE     'H'
#define BIOAUTH_OK_OPCODE     'I'
#define SEND_GPS_OPCODE       'J'
